### ISSUE TITLE
Add text field to copy variable names

### ISSUE THREAD

**Issue by CWempe** [fieldOfView/Cura-CustomJobPrefix#11]
It would be nice if there was an easy way to copy the variable names you want to use.

Currently you cannot select and `Ctrl+C` the variable names in the dialog.

![image](https://user-images.githubusercontent.com/1270359/80458298-dbf62a80-8930-11ea-96cd-022e7ff75edf.png)

If this is not possible in the dialog, maybe add a list of the available variables to the `README.md` and add a link in the dialog.

For now I use the source code.  
https://github.com/fieldOfView/Cura-CustomJobPrefix/blob/master/PrintInformationPatches.py#L75

**Comment by fieldOfView** [comment]
In the above linked commit, I have made the text selectable. I hope that in the future I'll have a better solution where eg clicking on the text will insert the replacementpattern into the textfield.
