### ISSUE TITLE
add one variable for full date time value

### ISSUE THREAD

**Issue by CWempe** [fieldOfView/Cura-CustomJobPrefix#13]
It would be nice to have one variable (`{date_year}`) that contains the whole date time.

like:
`2020-04-28_11:41`
`2020-04-28T11:41`
`20200428-1141`

You might want to check https://tools.ietf.org/html/rfc3339.
But I don't know if we need/want `time-second` and `time-offset`. (`2020-04-28T09:45:42+00:00`)

**Comment by fieldOfView** [comment]
The whole idea of splitting this up was to prevent debates about the order and format.
