### ISSUE TITLE
add 4-digit year variable

### ISSUE THREAD

**Issue by CWempe** [fieldOfView/Cura-CustomJobPrefix#14]
I would like to use a 4-digit year variable.

In fact I think this should be the default for `{date_year}`.
Bit I don't want to argue if the existing variable should be changed. 😉

**Comment by fieldOfView** [comment]
As a workaround, feel free to put the text `20` in front of the `{date_year}` variable. That should work for the next 80 years, and I hope this plugin is totally irrelevant by then.

**Comment by CWempe** [comment]
I accept that answer. 🙈
