### ISSUE TITLE
{time_iso} is invalid filename

### ISSUE THREAD

**Issue by CWempe** [fieldOfView/Cura-CustomJobPrefix#19]
Thanks for integrating `{time_iso}`.

But it produces an invalif failename because of the colons.

![image](https://user-images.githubusercontent.com/1270359/87247586-f9796180-c454-11ea-83f3-56c2e06d6320.png)

**Comment by fieldOfView** [comment]
Then you'll have to use the {time_hour} and {time_minutes} patterns.
I'll make sure to filter out colons in a future version, but that makes it impossible to use {time_iso}.

**Comment by CWempe** [comment]
Thanks.

Sorry, I did not think about colons in filenames in #13. 😇
