### ISSUE TITLE
Cropped checkbox setting in macOS

### ISSUE THREAD

**Issue by pjolayres** [fieldOfView/Cura-CustomJobPrefix#21]
![image](https://user-images.githubusercontent.com/23610081/89263110-3ce57b00-d663-11ea-98e1-61e84927cc67.png)

I can't seem to resize the window too. I can check and uncheck it. however, i cannot see the text. I know it's related to the underscore because I see it in windows.

**Comment by fieldOfView** [comment]
I'll fix this in the next version of the plugin.
