### ISSUE TITLE
Critical error in cura-git-4.8.0.r350.gfa4d1ba1fb

### ISSUE THREAD

**Issue by ustsv** [fieldOfView/Cura-CustomJobPrefix#24]
After this commit in cura git, critical error:
>SHA-1: fa4d1ba1fbe4685dbab21825c7fa0bcbdc889b36, &Номер ревизии ветви: 5022
>
>Don't strip accents from job name
>
>No idea why this was there in the first place. Our archeology attempts couldn't
>find out as to why it was introduced. We suspect an issue with other Qt versions.
>
>At least now ロボット.stl will not be mangled into ロホット.gcode upon saving (and
>german bears into bars)

`Traceback (most recent call last):
  File "C:/Users/name/AppData/Roaming/cura/4.8/plugins/CustomJobPrefix/CustomJobPrefix/PrintInformationPatches.py", line 120, in _triggerJobNameUpdate
    self._updateJobName()
  File "C:/Users/name/AppData/Roaming/cura/4.8/plugins/CustomJobPrefix/CustomJobPrefix/PrintInformationPatches.py", line 129, in _updateJobName
    base_name = self._print_information._stripAccents(self._print_information._base_name)
AttributeError: 'PrintInformation' object has no attribute '_stripAccents'`

**Comment by fieldOfView** [comment]
I would not recommend running Cura master, for exactly reasons like this. I already predicted this breakage when I saw the commit here: https://github.com/Ultimaker/Cura/commit/fa4d1ba1fbe4685dbab21825c7fa0bcbdc889b36 (see the comments)

I'll fix it.

**Comment by fieldOfView** [comment]
Should be fixed in 95e5bbf. I'll leave this issue open until a version containing this fix is available in the Marketplace.
