### ISSUE TITLE
Request: Default filetype?

### ISSUE THREAD

**Issue by thantik** [fieldOfView/Cura-CustomJobPrefix#25]
Would it be possible to add a feature to this plugin that would let you set the default exported filetype in Cura?

Default Cura doesn't seem to have the option and I initially (wrongly) assumed that's what postfix was supposed to do.

I understand now that it isn't, but thought it would fit the function of this plugin quite nicely.  Do you think you would be willing to implement functionality which would set the Cura default "Save As" filetype so you could select gcode, ufp, x3g, etc?

I notice the X3G plugin somehow manages to do this, but I can't pin down how.  I really just want to be able to save my files in UFP format for Klipper/Octoprint, and I don't like the Octoprint integration, and it's annoying to constantly have to change the filetype every time I save something.

**Comment by fieldOfView** [comment]
I don't know if this is a feature that should be part of this plugin. Then again, I would not know what plugin it should be part of. I was under the impression that once Cura exported a file as .ufp, that that would then be the default. Are you saying it is not? You may have to add `application/x-ufp` as a supported output format for your printer in the metadata section of the .def.json file, like so:
https://github.com/Ultimaker/Cura/blob/5.0/resources/definitions/ultimaker_s5.def.json#L9

> I don't like the Octoprint integration

As the author of the OctoPrint Connection plugin: BOOH! HISS! (is there anything I can do to improve it?)
