### ISSUE TITLE
Prefix is not changed in Cura 3.6 or 4.0

### ISSUE THREAD

**Issue by Ghostkeeper** [fieldOfView/Cura-CustomJobPrefix#5]
When changing the prefix, the actual job name of the slice is not changed accordingly. These are my reproduction steps:

1. Go to Extensions -> Custom printjob prefix -> Set prefix
2. Change the prefix to `{layer_height}x` and confirm the dialogue.
3. Load a model (in my case "cube.stl")

Expected result:
* Print job is called `0.1x_cube`.

Actual result:
* Print job is still called `UMS5_cube`.

This only reproduces in Cura 3.6 and 4.0. In 4.1+ it works fine. In 3.5 it crashes as per #4.

**Comment by fieldOfView** [comment]
Fixed in 561f4b7. Thanks for the extensive testing!
