### ISSUE TITLE
Add {profile_name} as a replacement pattern

### ISSUE THREAD

**Issue by mtw3d** [fieldOfView/Cura-CustomJobPrefix#6]
Would it be possible to add {profile_name} to the list of available replacement patterns? I don't like the way that Cura handles materials, so I use profiles for everything, so I have a profile name that probably already resembles the prefix that you are adding. I now am adding it manually when I save my files, but doing it automatically would be a huge benefit.

Thank you!

**Comment by fieldOfView** [comment]
It would be up to you to make sure your profile names are short then. I sort of want to prevent the prefixes to become comically long.

Note to self: don't forget about material display name.

**Comment by mtw3d** [comment]
That is reasonable. For my use case that would not be an issue, since everything I need is already included in my profile names. I use a profile name like "XL_0804_PLA" which tells me the printer it's for (my large format printer), the nozzle diameter and layer height (0.8mm and 0.4mm) and the material. The main thing I want is to be able to add that at the beginning of the file without having to manually add it everytime.

**Comment by xh3dx** [comment]
I would like to 2nd this request. I have different profiles and one of them is (for now) is optimized for use with OctoLapse, would like to be able to automatically have this information.

**Comment by DotNetRob** [comment]
I also 2nd the request, would be nice to have the profile in the name.

**Comment by fieldOfView** [comment]
It would help a lot if you could test this [development snapshot](https://storage.googleapis.com/ultimaker-cura-packages/v1/packages/CustomJobPrefix/FYpcfm4TiPBvM9MalbKhx8xChRWOkxXApUXx9HpFQUl4/CustomJobPrefix-v7.0.0-2020-06-12T14%3A24%3A08Z.curapackage?Expires=1907331855&GoogleAccessId=cura-packages%40stardust-193112.iam.gserviceaccount.com&Signature=RqfLeBBBYYDTs6OXvSdDhO77RDGBZqdXcB1G7f5sflY4dDRYY%2BhdTalAP21sNXcY%2BtTAseTK9XY%2F0yNo6MOfdoQbE01TRK7JkMrEZNwIMdY9WEvJPnbwGhSNXsyT8GeVgCPVEBdEegDKaSp3a89hSaNMTzelRXpFig2TkmlixdbgKvJQ96%2BEcLZ%2Fu9GIytIkZn7JlUwT4ELtQxPDh%2FKP5RF%2FvcNYIyVzjaRhBa5D1fUXRftRaAvYge89vAiyQ%2BYE8OhoW5lWUV7X3CWbzD%2F%2FiNdIhE2GQmx%2F5128YNLtI8WhnvMONaCMimZUaZ9Ez4jhTMiOcj%2BBucodWJ%2FOq3u3RQ%3D%3D) for me. Download the file and drag it onto the buildplate in Cura as if you were loading a 3d model.

**Comment by xh3dx** [comment]
Followed your instructions and loaded up a cal cube. Tested both {profile_name} and {profile_name_full}. They both work for me. Thank you for your work.

**Comment by fieldOfView** [comment]
Great, thanks for testing.

**Comment by mtw3d** [comment]
Works for me with {profile_name_full}. {profile_name} gave me unexpected results, but I assume it is exactly what you intended. The first letter and the last three letters (or possibly the last word) of the profile name.

Thank you!

**Comment by fieldOfView** [comment]
The {profile_name} one is abbreviated with the same rules that are also used for the printer name. It uses the first letter of each word, unless the word is 4 characters or fewer. Numbers are included as-is.
