### ISSUE TITLE
Add the Nozzle size

### ISSUE THREAD

**Issue by chatainsim** [fieldOfView/Cura-CustomJobPrefix#7]
Hello,
Can you also add the possibility to add the nozzle size in the filename ?

Thank you.

**Comment by fieldOfView** [comment]
This is already possible; use `{machine_nozzle_size}`.

**Comment by chatainsim** [comment]
Sorry, my bad.
Thanks

**Comment by fieldOfView** [comment]
Don't be. I like issues I have already fixed ;-)
