### ISSUE TITLE
How to change _ to something else

### ISSUE THREAD

**Issue by Ashteroide** [fieldOfView/Cura-CustomJobPrefix#8]
I want to know how to change _ between the prefix and job name to something smaller like . or ,
Anyone know how I can do this?

e.g. 1hr38min_Benchy -> 1hr38min.Benchy

**Comment by fieldOfView** [comment]
This currently can't be done without modifying the plugin. I'll make adding the `_` character between the prefix and the name optional. Then you can just enter the `.` or `,` at the end of the prefix.

**Comment by fieldOfView** [comment]
It would help a lot if you could test this [development snapshot](https://storage.googleapis.com/ultimaker-cura-packages/v1/packages/CustomJobPrefix/FYpcfm4TiPBvM9MalbKhx8xChRWOkxXApUXx9HpFQUl4/CustomJobPrefix-v7.0.0-2020-06-12T14%3A24%3A08Z.curapackage?Expires=1907331855&GoogleAccessId=cura-packages%40stardust-193112.iam.gserviceaccount.com&Signature=RqfLeBBBYYDTs6OXvSdDhO77RDGBZqdXcB1G7f5sflY4dDRYY%2BhdTalAP21sNXcY%2BtTAseTK9XY%2F0yNo6MOfdoQbE01TRK7JkMrEZNwIMdY9WEvJPnbwGhSNXsyT8GeVgCPVEBdEegDKaSp3a89hSaNMTzelRXpFig2TkmlixdbgKvJQ96%2BEcLZ%2Fu9GIytIkZn7JlUwT4ELtQxPDh%2FKP5RF%2FvcNYIyVzjaRhBa5D1fUXRftRaAvYge89vAiyQ%2BYE8OhoW5lWUV7X3CWbzD%2F%2FiNdIhE2GQmx%2F5128YNLtI8WhnvMONaCMimZUaZ9Ez4jhTMiOcj%2BBucodWJ%2FOq3u3RQ%3D%3D) for me. Download the file and drag it onto the buildplate in Cura as if you were loading a 3d model.

**Comment by Ashteroide** [comment]
Here is a screenshot, it looks to work pretty good, would I be able to hold onto it for daily testing so if I encounter some bugs I'll contact you?
![Screen Shot 2020-06-13 at 8 23 16 am](https://user-images.githubusercontent.com/56657815/84550901-3e738080-ad4f-11ea-851e-7b013103a1af.png)

**Comment by fieldOfView** [comment]
Great, thanks for testing. I see you also found the postfix.

Sure, you can keep using this version, no problem. When I do a new official release, the Marketplace will show it as an update. By the way, there's an update waiting for you ;-)

**Comment by Ashteroide** [comment]
@fieldOfView Cura didn't show an update and also when I clear the prefix the postfix doesn't show as well and the prefix is set to I3MEGA for me
![Screen Shot 2020-06-13 at 11 41 02 pm](https://user-images.githubusercontent.com/56657815/84570222-5985d500-adcf-11ea-8323-e37a0efd0be0.png)

**Comment by fieldOfView** [comment]
> Cura didn't show an update

The development snapshot is a preview release that is not available through the Marketplace.

> when I clear the prefix the postfix doesn't show as well 

Very well spotted. When I read the "when I clear the prefix" part I knew exactly what you were going to say and what I did wrong. I'll get this fixed.

**Comment by Ashteroide** [comment]
How are you going with the little buggies? I'm glad to be able to test a development version :)

**Comment by fieldOfView** [comment]
I appreciate the eagerness, but I do sometimes need a couple of hours to enjoy the weekend.

I fixed this oversight here:
https://github.com/fieldOfView/Cura-CustomJobPrefix/commit/5dbb9307b1a644d1e63ee34bcddac15380bea927#diff-0c6f39ca214c9a41217164c3111736fbR115

**Comment by Ashteroide** [comment]
Apologies for my eagerness, I will wait patiently for you

**Comment by Ashteroide** [comment]
Hey I found another bug, I'll upload a screenshot, the original STL was named Case1;2 which I suspect would be because of the ; but when I save the Gcode it removes the actual name of it and just puts the prefix
![Screen Shot 2020-06-20 at 2 33 45 pm](https://user-images.githubusercontent.com/56657815/85191758-5d4fb500-b303-11ea-9706-545716f3855a.png)

**Comment by fieldOfView** [comment]
Could you open a new issue for that, and include the values you used for the prefix and postfix?
